import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          <div>
              <Link href="/learn/angular"
                    className={styles.card}
                    rel="noopener noreferrer"
              >
                  <h2>
                      Learn Angular
                  </h2>
              </Link>
              <Link href="/learn/vue"
                    className={styles.card}
                    rel="noopener noreferrer"
              >
                  <h2>
                      Learn Vue JS
                  </h2>
              </Link>
              <Link href="/learn/react"
                    className={styles.card}
                    rel="noopener noreferrer"
              >
                  <h2>
                      Learn React JS
                  </h2>
              </Link>
              <Link href="/learn/next"
                    className={styles.card}
                    rel="noopener noreferrer"
              >
                  <h2>
                      Learn Next JS
                  </h2>
              </Link>
          </div>
      </main>
    </>
  );
}
